First strategy:

- calculate the mean of candles size, in order to find which candle is bigger than mean of candles

- calculate the mean of volumes bar size, in order to find which volume bar is bigger than mean of volumes bar

- check if after this candle the price market became lower or higher

In [122]:
#pip install --upgrade notebook

In [123]:
import pandas as pd
import numpy as np
import yfinance as yf
import datetime as dt




# fetch historical data
start = dt.datetime(2015,1,1)
end = dt.datetime.now()
stock_data = yf.download('TAEE11.SA', start, end, interval='1d')

stock_data

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close   Volume
Date
2015-01-02  19.000000  19.049999  18.219999  18.850000   7.203686   344100
2015-01-05  18.469999  19.049999  18.120001  18.780001   7.176933   485100
2015-01-06  18.900000  19.139999  18.610001  18.809999   7.188399   634700
2015-01-07  18.950001  19.150000  18.760000  18.840000   7.199866   349000
2015-01-08  18.799999  19.379999  18.780001  19.020000   7.268653   557700
...               ...        ...        ...        ...        ...      ...
2024-05-27  35.299999  35.439999  35.000000  35.070000  35.070000  1124100
2024-05-28  35.180000  35.349998  34.880001  34.880001  34.880001  1068500
2024-05-29  34.900002  34.939999  34.560001  34.560001  34.560001  1658200
2024-05-31  34.599998  34.689999  34.279999  34.279999  34.279999  1441700
2024-06-03  33.889999  34.430000  33.250000  34.270000  34.270000  8117600

[2341 rows x 6 columns]

In [124]:
stock_data["Size Candle"] = np.abs(stock_data["Close"] - stock_data["Open"])

stock_data.tail(20)

,Open,High,Low,Close,Adj Close,Volume,Size Candle
Date,,,,,,,
2024-05-06,34.959999,35.779999,34.520000,35.560001,35.132679,5025800,0.600002
2024-05-07,35.689999,35.740002,35.340000,35.340000,34.915321,2152900,0.349998
2024-05-08,35.380001,35.689999,35.369999,35.650002,35.221600,2210500,0.270000
2024-05-09,35.610001,35.619999,34.610001,34.810001,34.391693,4533700,0.799999
2024-05-10,35.000000,35.230000,34.619999,34.619999,34.203976,3272700,0.380001
2024-05-13,34.790001,35.020000,34.709999,35.000000,34.579411,1304400,0.209999
2024-05-14,34.639999,35.000000,34.619999,35.000000,35.000000,2061600,0.360001
2024-05-15,34.950001,35.119999,34.759998,35.009998,35.009998,1732600,0.059998
2024-05-16,35.090000,35.250000,35.000000,35.000000,35.000000,3164500,0.090000
2024-05-17,35.060001,35.110001,34.849998,34.849998,34.849998,1429400,0.210003
2024-05-20,34.900002,35.400002,34.759998,35.400002,35.400002,1617500,0.500000
2024-05-21,35.400002,35.759998,35.270000,35.750000,35.750000,1585400,0.349998
2024-05-22,35.689999,35.730000,35.439999,35.459999,35.459999,2143500,0.230000
2024-05-23,35.439999,35.450001,34.970001,34.970001,34.970001,1707800,0.469997
2024-05-24,35.080002,35.619999,35.020000,35.299999,35.299999,1590500,0.219997
2024-05-27,35.299999,35.439999,35.000000,35.070000,35.070000,1124100,0.230000
2024-05-28,35.180000,35.349998,34.880001,34.880001,34.880001,1068500,0.299999
2024-05-29,34.900002,34.939999,34.560001,34.560001,34.560001,1658200,0.340000
2024-05-31,34.599998,34.689999,34.279999,34.279999,34.279999,1441700,0.320000
2024-06-03,33.889999,34.430000,33.250000,34.270000,34.270000,8117600,0.380001

In [125]:
# check candle mean
stock_data["Mean Size Candle"] = stock_data['Size Candle'].rolling(100).quantile(0.9)
# check volume mean
stock_data["Mean Size Volume"] = stock_data['Volume'].rolling(100).quantile(0.9)
# check sign
stock_data["Sign"] = np.sign(stock_data["Close"] - stock_data["Open"])

stock_data.tail(20)

,Open,High,Low,Close,Adj Close,Volume,Size Candle,Mean Size Candle,Mean Size Volume,Sign
Date,,,,,,,,,,
2024-05-06,34.959999,35.779999,34.520000,35.560001,35.132679,5025800,0.600002,0.434000,2773660.0,1.0
2024-05-07,35.689999,35.740002,35.340000,35.340000,34.915321,2152900,0.349998,0.434000,2773660.0,-1.0
2024-05-08,35.380001,35.689999,35.369999,35.650002,35.221600,2210500,0.270000,0.434000,2773660.0,1.0
2024-05-09,35.610001,35.619999,34.610001,34.810001,34.391693,4533700,0.799999,0.470001,2829430.0,-1.0
2024-05-10,35.000000,35.230000,34.619999,34.619999,34.203976,3272700,0.380001,0.434000,2993890.0,-1.0
2024-05-13,34.790001,35.020000,34.709999,35.000000,34.579411,1304400,0.209999,0.434000,2993890.0,1.0
2024-05-14,34.639999,35.000000,34.619999,35.000000,35.000000,2061600,0.360001,0.434000,2829430.0,1.0
2024-05-15,34.950001,35.119999,34.759998,35.009998,35.009998,1732600,0.059998,0.434000,2829430.0,1.0
2024-05-16,35.090000,35.250000,35.000000,35.000000,35.000000,3164500,0.090000,0.424998,2993890.0,-1.0
2024-05-17,35.060001,35.110001,34.849998,34.849998,34.849998,1429400,0.210003,0.424998,2993890.0,-1.0
2024-05-20,34.900002,35.400002,34.759998,35.400002,35.400002,1617500,0.500000,0.470001,2993890.0,1.0
2024-05-21,35.400002,35.759998,35.270000,35.750000,35.750000,1585400,0.349998,0.470001,2993890.0,1.0
2024-05-22,35.689999,35.730000,35.439999,35.459999,35.459999,2143500,0.230000,0.470001,2993890.0,-1.0
2024-05-23,35.439999,35.450001,34.970001,34.970001,34.970001,1707800,0.469997,0.470001,2993890.0,-1.0
2024-05-24,35.080002,35.619999,35.020000,35.299999,35.299999,1590500,0.219997,0.470001,2993890.0,1.0
2024-05-27,35.299999,35.439999,35.000000,35.070000,35.070000,1124100,0.230000,0.470001,2993890.0,-1.0
2024-05-28,35.180000,35.349998,34.880001,34.880001,34.880001,1068500,0.299999,0.470001,2993890.0,-1.0
2024-05-29,34.900002,34.939999,34.560001,34.560001,34.560001,1658200,0.340000,0.470001,2993890.0,-1.0
2024-05-31,34.599998,34.689999,34.279999,34.279999,34.279999,1441700,0.320000,0.470001,2993890.0,-1.0
2024-06-03,33.889999,34.430000,33.250000,34.270000,34.270000,8117600,0.380001,0.470001,3072430.0,1.0

In [126]:
cond1 = stock_data["Size Candle"] > stock_data["Mean Size Candle"]
cond2 = stock_data["Volume"] > stock_data["Mean Size Volume"]
cond3 = stock_data["Sign"] == -1

conditions_met = stock_data[cond1 & cond2 & cond3]

In [127]:
# build a plot

2016-11-10 00:00:00

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed